### ISSUE TITLE
Why uncorrected sigma bond order is enhanced with coefficient `cutoff`?

### ISSUE THREAD

**Issue by shishaochen** [cagrikymk/JAX-ReaxFF#4]
According to equations of ReaxFF, the weight of sigma bond order is 1. However, JAX-ReaxFF add a coefficient `cutoff`.
```python
ehulp = (1 + cutoff) * np.exp(bop1 * rh2)
```

Related codes:
- https://github.com/cagrikymk/JAX-ReaxFF/blob/master/jaxreaxff/helper.py#L164
- https://github.com/cagrikymk/JAX-ReaxFF/blob/master/jaxreaxff/reaxffpotential.py#L1080
- https://github.com/cagrikymk/JAX-ReaxFF/blob/master/jaxreaxff/reaxffpotential.py#L1133

Could you please tell the reason?

**Comment by cagrikymk** [comment]
My main references are the Fortran implementation (written by Dr. Adri van Duin) and the PuReMD code. 
Since these implementations use that formula, I stick to it as well.

Here is a reference to compare (from the Fortran code):
[https://github.com/CFDEMproject/LAMMPS/blob/master/lib/reax/reax_connect.F#L742](url)

**Comment by shishaochen** [comment]
@cagrikymk Got it. Thx.
